export const EXTRACTED_BASELINE_ROWS = [
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Electric",
    "shiftName": "Opening Shift (11:00am)",
    "positionName": "Waiter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Electric",
    "shiftName": "Afternoon Shift (1:00 PM)",
    "positionName": "Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 6
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Electric",
    "shiftName": "Afternoon Shift (2:00 PM)",
    "positionName": "Bartender",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Electric",
    "shiftName": "Evening Shift (3pm)",
    "positionName": "Waiter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 2,
    "mon": 2,
    "tue": 2,
    "wed": 2,
    "thu": 2,
    "fri": 2,
    "sat": 2,
    "weeklyTotal": 14
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Electric",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "5.7263157894736842",
    "sun": 4,
    "mon": 5,
    "tue": 5,
    "wed": 5,
    "thu": 5,
    "fri": 5,
    "sat": 5,
    "weeklyTotal": 34
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Ceecconi's",
    "shiftName": "Middle Shift (12:00 Noon)",
    "positionName": "Restaurant Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 0,
    "tue": 0,
    "wed": 0,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 3
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Ceecconi's",
    "shiftName": "Middle Shift (12:00 Noon)",
    "positionName": "Bartender",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Ceecconi's",
    "shiftName": "Middle Shift (12:00 Noon)",
    "positionName": "Waiter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 2,
    "mon": 2,
    "tue": 2,
    "wed": 3,
    "thu": 3,
    "fri": 3,
    "sat": 3,
    "weeklyTotal": 18
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Ceecconi's",
    "shiftName": "Evening Shift (4:00Pm)",
    "positionName": "Supervisor",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Ceecconi's",
    "shiftName": "Evening Shift (4:00pm)",
    "positionName": "Waiter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 2,
    "mon": 2,
    "tue": 2,
    "wed": 1,
    "thu": 2,
    "fri": 2,
    "sat": 2,
    "weeklyTotal": 13
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Ceecconi's",
    "shiftName": "Middle Shift (12:00 Noon)",
    "positionName": "Hostess",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Ceecconi's",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "9.2631578947368425",
    "sun": 7,
    "mon": 7,
    "tue": 7,
    "wed": 7,
    "thu": 9,
    "fri": 9,
    "sat": 9,
    "weeklyTotal": 55
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Kaia",
    "shiftName": "Opening Shift (11:00am)",
    "positionName": "Headwaiter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Kaia",
    "shiftName": "Middle Shift (12:00 Noon)",
    "positionName": "Hostess",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Kaia",
    "shiftName": "Middle Shift (12:00 Noon)",
    "positionName": "Assistant Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 6
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Kaia",
    "shiftName": "Evening Shift (3:00pm)",
    "positionName": "Bartender",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Kaia",
    "shiftName": "Evening Shift (4:00pm)",
    "positionName": "Supervisor",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Kaia",
    "shiftName": "Evening Shift (4:00pm)",
    "positionName": "Waiter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Kaia",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "6.905263157894737",
    "sun": 5,
    "mon": 6,
    "tue": 6,
    "wed": 6,
    "thu": 6,
    "fri": 6,
    "sat": 6,
    "weeklyTotal": 41
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Millies",
    "shiftName": "Morning Shift (10:00 AM)",
    "positionName": "RGM",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 0,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 5
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Millies",
    "shiftName": "Morning Shift (05:00 AM)",
    "positionName": "Bartender",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Millies",
    "shiftName": "Morning Shift (05:00 AM)",
    "positionName": "Waiter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Millies",
    "shiftName": "Morning Shift (07:00 AM)",
    "positionName": "Waiter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 2,
    "mon": 2,
    "tue": 2,
    "wed": 2,
    "thu": 2,
    "fri": 2,
    "sat": 2,
    "weeklyTotal": 14
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Millies",
    "shiftName": "Morning Shift (07:00 AM)",
    "positionName": "Hostess",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Millies",
    "shiftName": "Morning Shift (07:00 AM)",
    "positionName": "Supervisor",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Millies",
    "shiftName": "Morning Shift (08:00 AM)",
    "positionName": "Assistant Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 0,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 6
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Millies",
    "shiftName": "Afternoon Shift (4:00pm)",
    "positionName": "Supervisor",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Millies",
    "shiftName": "Afternoon Shift (2:00 PM)",
    "positionName": "Waiter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 3,
    "mon": 3,
    "tue": 3,
    "wed": 3,
    "thu": 3,
    "fri": 3,
    "sat": 3,
    "weeklyTotal": 21
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Millies",
    "shiftName": "Afternoon Shift (2:00 PM)",
    "positionName": "Bartender",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Millies",
    "shiftName": "Afternoon Shift (3:00 PM)",
    "positionName": "Assistant Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 0,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 6
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Millies",
    "shiftName": "Evening Shift (4:00pm)",
    "positionName": "Bartender",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Millies",
    "shiftName": "Evening Shift (4:00 pm)",
    "positionName": "Waiter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 5,
    "mon": 5,
    "tue": 5,
    "wed": 5,
    "thu": 5,
    "fri": 5,
    "sat": 5,
    "weeklyTotal": 35
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Millies",
    "shiftName": "Evening Shift (4:00 pm)",
    "positionName": "Hostess",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 2,
    "mon": 2,
    "tue": 2,
    "wed": 2,
    "thu": 2,
    "fri": 2,
    "sat": 2,
    "weeklyTotal": 14
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Millies",
    "shiftName": "Evening Shift (4:00pm)",
    "positionName": "Supervisor",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Millies",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "26.442105263157895",
    "sun": 22,
    "mon": 22,
    "tue": 22,
    "wed": 22,
    "thu": 23,
    "fri": 23,
    "sat": 23,
    "weeklyTotal": 157
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Malibu",
    "shiftName": "Morning Shift (10:00 am)",
    "positionName": "Waiter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Malibu",
    "shiftName": "Morning Shift (10:00 am)",
    "positionName": "Bartender",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Malibu",
    "shiftName": "Middle Shift (11:00 am)",
    "positionName": "Supervisor",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Malibu",
    "shiftName": "Afternoon Shift (1:00 Pm)",
    "positionName": "Hostess",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Malibu",
    "shiftName": "Afternoon Shift (15:00 pm)",
    "positionName": "Supervisor",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Malibu",
    "shiftName": "Afternoon Shift (15:00 pm)",
    "positionName": "Bartender",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Malibu",
    "shiftName": "Afternoon Shift (15:00 pm)",
    "positionName": "Waiter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Malibu",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "8.2526315789473692",
    "sun": 7,
    "mon": 7,
    "tue": 7,
    "wed": 7,
    "thu": 7,
    "fri": 7,
    "sat": 7,
    "weeklyTotal": 49
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Hadika",
    "shiftName": "Opening Shift (11:00am)",
    "positionName": "Waiter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Hadika",
    "shiftName": "Middle Shift (12:00 am)",
    "positionName": "Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 0,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 5
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Hadika",
    "shiftName": "Afternoon Shift (3:00 pm)",
    "positionName": "Waiter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 2,
    "mon": 2,
    "tue": 1,
    "wed": 2,
    "thu": 2,
    "fri": 2,
    "sat": 2,
    "weeklyTotal": 13
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Hadika",
    "shiftName": "Afternoon Shift (3:00 pm)",
    "positionName": "Hostess",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Hadika",
    "shiftName": "Afternoon Shift (3:00 pm)",
    "positionName": "Bartender",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Hadika",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "6.5684210526315789",
    "sun": 5,
    "mon": 5,
    "tue": 5,
    "wed": 6,
    "thu": 6,
    "fri": 6,
    "sat": 6,
    "weeklyTotal": 39
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "Cake Shop",
    "shiftName": "Middle Shift (8:00 AM)",
    "positionName": "Shop Assistant",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "Cake Shop",
    "shiftName": "Middle Shift (12:00 PM)",
    "positionName": "Supervisor",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "Cake Shop",
    "shiftName": "Evening Shift (02:00 PM)",
    "positionName": "Shop Assistant",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "Cake Shop",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "3.5368421052631578",
    "sun": 3,
    "mon": 3,
    "tue": 3,
    "wed": 3,
    "thu": 3,
    "fri": 3,
    "sat": 3,
    "weeklyTotal": 21
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Banquet",
    "shiftName": "Morning Shift (08:00 AM)",
    "positionName": "Waiter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 2,
    "mon": 2,
    "tue": 2,
    "wed": 2,
    "thu": 2,
    "fri": 2,
    "sat": 2,
    "weeklyTotal": 14
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Banquet",
    "shiftName": "Morning Shift (08:00 AM)",
    "positionName": "Supervisor",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Banquet",
    "shiftName": "Morning Shift (08:00 AM)",
    "positionName": "BQT director",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 0,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 5
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Banquet",
    "shiftName": "Evening Shift (03:00 PM)",
    "positionName": "Waiter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Banquet",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "5.5578947368421057",
    "sun": 4,
    "mon": 4,
    "tue": 5,
    "wed": 5,
    "thu": 5,
    "fri": 5,
    "sat": 5,
    "weeklyTotal": 33
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - IRD",
    "shiftName": "Morning Shift (08:00 AM)",
    "positionName": "Waiter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - IRD",
    "shiftName": "Morning Shift (10:00 AM)",
    "positionName": "Waiter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - IRD",
    "shiftName": "Afternoon Shift (2:00 PM)",
    "positionName": "Assistant Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 6
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - IRD",
    "shiftName": "Evening Shift (3:00 pm)",
    "positionName": "Waiter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 2,
    "mon": 2,
    "tue": 2,
    "wed": 2,
    "thu": 2,
    "fri": 2,
    "sat": 2,
    "weeklyTotal": 14
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - IRD",
    "shiftName": "Night Shift (11:00pm)",
    "positionName": "Waiter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - IRD",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "6.905263157894737",
    "sun": 5,
    "mon": 6,
    "tue": 6,
    "wed": 6,
    "thu": 6,
    "fri": 6,
    "sat": 6,
    "weeklyTotal": 41
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Admin",
    "shiftName": "Morning Shift (08:00 AM)",
    "positionName": "Assist F&B Director",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 0,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 0,
    "weeklyTotal": 4
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Admin",
    "shiftName": "Morning Shift (10:00 AM)",
    "positionName": "F&B Cooredinator",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 5
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Admin",
    "shiftName": "Afternoon Shift (2:00 PM)",
    "positionName": "AV Technician",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 0,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 5
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Admin",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "2.357894736842105",
    "sun": 1,
    "mon": 1,
    "tue": 3,
    "wed": 3,
    "thu": 3,
    "fri": 2,
    "sat": 1,
    "weeklyTotal": 14
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Ned Club",
    "shiftName": "Morning Shift (10:00 AM)",
    "positionName": "Restaurant General Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 0,
    "sat": 1,
    "weeklyTotal": 6
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Ned Club",
    "shiftName": "Morning Shift (11:00 AM)",
    "positionName": "Restaurant Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 0,
    "tue": 0,
    "wed": 0,
    "thu": 0,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 0
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Ned Club",
    "shiftName": "Afternon Shift (1:00 PM)",
    "positionName": "Assistant Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 0,
    "tue": 0,
    "wed": 0,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 3
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Ned Club",
    "shiftName": "Morning Shift (08:00 AM)",
    "positionName": "Supervisor",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 0,
    "tue": 0,
    "wed": 0,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 3
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Ned Club",
    "shiftName": "Morning Shift (09:00 AM)",
    "positionName": "Head Waiter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 0,
    "tue": 0,
    "wed": 0,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 3
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Ned Club",
    "shiftName": "Morning Shift (07:00 AM)",
    "positionName": "Waiter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 0,
    "tue": 0,
    "wed": 0,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 3
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Ned Club",
    "shiftName": "Morning Shift (08:00 AM)",
    "positionName": "Hostess",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 0,
    "tue": 0,
    "wed": 0,
    "thu": 1,
    "fri": 1,
    "sat": 0,
    "weeklyTotal": 2
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Ned Club",
    "shiftName": "Morning Shift (08:00AM)",
    "positionName": "Head Bartender",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 0,
    "tue": 0,
    "wed": 0,
    "thu": 1,
    "fri": 0,
    "sat": 1,
    "weeklyTotal": 2
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Ned Club",
    "shiftName": "Afternoon Shift (4:00 PM)",
    "positionName": "Supervisor",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Ned Club",
    "shiftName": "Evening Shift (4:00PM)",
    "positionName": "Head Waiter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 2,
    "mon": 2,
    "tue": 2,
    "wed": 2,
    "thu": 1,
    "fri": 2,
    "sat": 2,
    "weeklyTotal": 13
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Ned Club",
    "shiftName": "Evening Shift (4:00 PM)",
    "positionName": "Waiter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 3,
    "mon": 3,
    "tue": 3,
    "wed": 3,
    "thu": 2,
    "fri": 3,
    "sat": 2,
    "weeklyTotal": 19
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Ned Club",
    "shiftName": "Evening Shift (4:00PM)",
    "positionName": "Barista",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Ned Club",
    "shiftName": "Evening Shift (4:00PM)",
    "positionName": "Hostess",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "F&B - Ned Club",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "12.631578947368421",
    "sun": 9,
    "mon": 9,
    "tue": 9,
    "wed": 9,
    "thu": 13,
    "fri": 13,
    "sat": 13,
    "weeklyTotal": 75
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "Total Count per Day",
    "shiftName": "Total employees needed in F&B",
    "positionName": "94.147368421052647",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 71,
    "mon": 74,
    "tue": 75,
    "wed": 76,
    "thu": 83,
    "fri": 83,
    "sat": 83,
    "weeklyTotal": 0
  },
  {
    "mainDepartment": "F&B",
    "sheetName": "F&B",
    "subDepartment": "Total Count per Day",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "5.7263157894736842",
    "sun": 0,
    "mon": 0,
    "tue": 0,
    "wed": 0,
    "thu": 0,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 0
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Neds Club",
    "shiftName": "Morning Shift (06:00 AM)",
    "positionName": "DCDP",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Neds Club",
    "shiftName": "Morning shift (11:00 AM)",
    "positionName": "Jr. Sous Chef and CDP",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 2,
    "mon": 2,
    "tue": 2,
    "wed": 2,
    "thu": 2,
    "fri": 2,
    "sat": 2,
    "weeklyTotal": 14
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Neds Club",
    "shiftName": "After Noon Shift (3:00pm)",
    "positionName": "CDP and Commi",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 2,
    "mon": 2,
    "tue": 2,
    "wed": 2,
    "thu": 2,
    "fri": 2,
    "sat": 2,
    "weeklyTotal": 14
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Neds Club",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "5.8947368421052628",
    "sun": 5,
    "mon": 5,
    "tue": 5,
    "wed": 5,
    "thu": 5,
    "fri": 5,
    "sat": 5,
    "weeklyTotal": 35
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Pastry",
    "shiftName": "Morning Shift (08:00 AM)",
    "positionName": "Bakery and Pastry",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 2,
    "mon": 2,
    "tue": 2,
    "wed": 2,
    "thu": 2,
    "fri": 2,
    "sat": 2,
    "weeklyTotal": 14
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Pastry",
    "shiftName": "Morning shift (10:00 AM)",
    "positionName": "Executive Pastry chef, Or Sous Chef",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Pastry",
    "shiftName": "After Noon Shift (2:00pm)",
    "positionName": "Pastry",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Pastry",
    "shiftName": "Evening Shift (4:00pm)",
    "positionName": "Pastry",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Pastry",
    "shiftName": "Night Shift (23:00 Pm)",
    "positionName": "Bakery",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Pastry",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "7.0736842105263156",
    "sun": 6,
    "mon": 6,
    "tue": 6,
    "wed": 6,
    "thu": 6,
    "fri": 6,
    "sat": 6,
    "weeklyTotal": 42
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Millies",
    "shiftName": "Morning Shift (06:00 AM)",
    "positionName": "CDP",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Millies",
    "shiftName": "Morning shift (08:00 AM)",
    "positionName": "CDP and Sr. Chef",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 2,
    "mon": 2,
    "tue": 2,
    "wed": 2,
    "thu": 2,
    "fri": 2,
    "sat": 2,
    "weeklyTotal": 14
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Millies",
    "shiftName": "After Noon Shift (2:00pm)",
    "positionName": "Commis and Intern",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 2,
    "mon": 2,
    "tue": 2,
    "wed": 2,
    "thu": 2,
    "fri": 2,
    "sat": 2,
    "weeklyTotal": 14
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Millies",
    "shiftName": "Evening Shift (4:00pm)",
    "positionName": "CDP",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 2,
    "mon": 2,
    "tue": 2,
    "wed": 2,
    "thu": 2,
    "fri": 2,
    "sat": 2,
    "weeklyTotal": 14
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Millies",
    "shiftName": "Night Shift (23:00 Pm)",
    "positionName": "DCDP",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Millies",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "9.4315789473684202",
    "sun": 8,
    "mon": 8,
    "tue": 8,
    "wed": 8,
    "thu": 8,
    "fri": 8,
    "sat": 8,
    "weeklyTotal": 56
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Cecconis",
    "shiftName": "Morning Shift (10:00 AM)",
    "positionName": "Head Chef, Jr. Sous, CDP, DCDP",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 4,
    "mon": 3,
    "tue": 3,
    "wed": 3,
    "thu": 3,
    "fri": 3,
    "sat": 3,
    "weeklyTotal": 22
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Cecconis",
    "shiftName": "Afternoon shift (3:00 PM)",
    "positionName": "CDP, DCDP, Commis",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 3,
    "mon": 2,
    "tue": 2,
    "wed": 2,
    "thu": 2,
    "fri": 2,
    "sat": 2,
    "weeklyTotal": 15
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Cecconis",
    "shiftName": "Evening Shift (6:00pm)",
    "positionName": "Commis",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Cecconis",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "7.4105263157894736",
    "sun": 8,
    "mon": 6,
    "tue": 6,
    "wed": 6,
    "thu": 6,
    "fri": 6,
    "sat": 6,
    "weeklyTotal": 44
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Electric",
    "shiftName": "Morning Shift (10:00 AM)",
    "positionName": "Commis",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Electric",
    "shiftName": "Mid shift ( 12:00 PM)",
    "positionName": "Sr. CDP",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Electric",
    "shiftName": "Evening Shift (3:00pm)",
    "positionName": "DCDP",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 2,
    "mon": 2,
    "tue": 2,
    "wed": 2,
    "thu": 2,
    "fri": 2,
    "sat": 2,
    "weeklyTotal": 14
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Electric",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "4.7157894736842101",
    "sun": 4,
    "mon": 4,
    "tue": 4,
    "wed": 4,
    "thu": 4,
    "fri": 4,
    "sat": 4,
    "weeklyTotal": 28
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Kaia",
    "shiftName": "Morning Shift (10:00 AM)",
    "positionName": "DCDP",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Kaia",
    "shiftName": "Mid Shift (12:00 AM)",
    "positionName": "CDP",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 3,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 9
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Kaia",
    "shiftName": "Closing (2:00pm)",
    "positionName": "DCDP & CDP",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 2,
    "mon": 2,
    "tue": 2,
    "wed": 2,
    "thu": 3,
    "fri": 2,
    "sat": 2,
    "weeklyTotal": 15
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Kaia",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "5.2210526315789476",
    "sun": 4,
    "mon": 4,
    "tue": 4,
    "wed": 4,
    "thu": 7,
    "fri": 4,
    "sat": 4,
    "weeklyTotal": 31
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Malibu",
    "shiftName": "Morning Shift (10:00 AM)",
    "positionName": "Commis",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 2,
    "sat": 1,
    "weeklyTotal": 8
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Malibu",
    "shiftName": "Middle shift (12:00 PM)",
    "positionName": "Sous Chef and Commi",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 2,
    "sat": 1,
    "weeklyTotal": 8
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Malibu",
    "shiftName": "Evening  Shift (2:00pm)",
    "positionName": "CDP & Commis",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 2,
    "mon": 2,
    "tue": 2,
    "wed": 2,
    "thu": 2,
    "fri": 2,
    "sat": 2,
    "weeklyTotal": 14
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Malibu",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "5.0526315789473681",
    "sun": 4,
    "mon": 4,
    "tue": 4,
    "wed": 4,
    "thu": 4,
    "fri": 6,
    "sat": 4,
    "weeklyTotal": 30
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Hadika",
    "shiftName": "Morning Shift (11:00 AM)",
    "positionName": "DCDP",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Hadika",
    "shiftName": "Afternoon shift (15:00 PM)",
    "positionName": "Sous Chef",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Hadika",
    "shiftName": "Evening Shift (4:00pm)",
    "positionName": "Pastry",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 2,
    "mon": 2,
    "tue": 2,
    "wed": 2,
    "thu": 2,
    "fri": 2,
    "sat": 2,
    "weeklyTotal": 14
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Hadika",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "4.7157894736842101",
    "sun": 4,
    "mon": 4,
    "tue": 4,
    "wed": 4,
    "thu": 4,
    "fri": 4,
    "sat": 4,
    "weeklyTotal": 28
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Banquet",
    "shiftName": "Morning Shift (06:00 AM)",
    "positionName": "Sr. CDP Staff Dining",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Banquet",
    "shiftName": "Morning shift (11:00 AM)",
    "positionName": "Sous Chef staff dining",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Banquet",
    "shiftName": "After Noon Shift (3:00pm)",
    "positionName": "Commi staff dining",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 6
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Banquet",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "3.3684210526315788",
    "sun": 2,
    "mon": 3,
    "tue": 3,
    "wed": 3,
    "thu": 3,
    "fri": 3,
    "sat": 3,
    "weeklyTotal": 20
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - QIA",
    "shiftName": "Morning shift (11:00 PM)",
    "positionName": "Sous Chef",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 0,
    "sat": 1,
    "weeklyTotal": 6
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - QIA",
    "shiftName": "After Noon Shift (3:00pm) -",
    "positionName": "Sous Chef Commi",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 3,
    "mon": 3,
    "tue": 3,
    "wed": 3,
    "thu": 3,
    "fri": 0,
    "sat": 2,
    "weeklyTotal": 17
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - QIA",
    "shiftName": "Evening Shift (09:00 PM) -",
    "positionName": "Sr. CDP Staff Dining",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 2,
    "mon": 2,
    "tue": 2,
    "wed": 2,
    "thu": 2,
    "fri": 0,
    "sat": 2,
    "weeklyTotal": 12
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - QIA",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "5.8947368421052628",
    "sun": 6,
    "mon": 6,
    "tue": 6,
    "wed": 6,
    "thu": 6,
    "fri": 0,
    "sat": 5,
    "weeklyTotal": 35
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Butchery",
    "shiftName": "Morning shift (08:00 AM)",
    "positionName": "Chef de Partie",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Butchery",
    "shiftName": "Morning shift (08:00 AM)",
    "positionName": "Commi",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "CUL - Butchery",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "2.357894736842105",
    "sun": 2,
    "mon": 2,
    "tue": 2,
    "wed": 2,
    "thu": 2,
    "fri": 2,
    "sat": 2,
    "weeklyTotal": 14
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "BOH - Stewarding",
    "shiftName": "Morning shift (8:00",
    "positionName": "Chief Steward",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 5
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "BOH - Stewarding",
    "shiftName": "After Noon Shift (3:00pm) - Sous Chef Commi",
    "positionName": "Asistant Chief Steward",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 6
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "BOH - Stewarding",
    "shiftName": "Morning shift (8:00",
    "positionName": "Supervisor",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 0,
    "sat": 1,
    "weeklyTotal": 6
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "BOH - Stewarding",
    "shiftName": "Morning shift (8:01",
    "positionName": "Steward",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 2,
    "mon": 1,
    "tue": 1,
    "wed": 2,
    "thu": 2,
    "fri": 2,
    "sat": 2,
    "weeklyTotal": 12
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "BOH - Stewarding",
    "shiftName": "Afternoon",
    "positionName": "Supervisor",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "BOH - Stewarding",
    "shiftName": "Afternoon",
    "positionName": "Steward",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 2,
    "mon": 2,
    "tue": 2,
    "wed": 2,
    "thu": 2,
    "fri": 2,
    "sat": 2,
    "weeklyTotal": 14
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "BOH - Stewarding",
    "shiftName": "Night Shift (23:00)",
    "positionName": "Supervisor",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "BOH - Stewarding",
    "shiftName": "Night Shift",
    "positionName": "Steward",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 5,
    "mon": 5,
    "tue": 5,
    "wed": 5,
    "thu": 5,
    "fri": 5,
    "sat": 5,
    "weeklyTotal": 35
  },
  {
    "mainDepartment": "CUL",
    "sheetName": "CUL",
    "subDepartment": "BOH - Stewarding",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "15",
    "sun": 13,
    "mon": 13,
    "tue": 13,
    "wed": 14,
    "thu": 14,
    "fri": 12,
    "sat": 13,
    "weeklyTotal": 92
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Front Office",
    "shiftName": "Morning Shift (8 AM- 5 PM)",
    "positionName": "Duty Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Front Office",
    "shiftName": "Morning Shift (8 AM-5 PM)",
    "positionName": "Receptionist",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Front Office",
    "shiftName": "Morning Shift (8 AM-5 PM)",
    "positionName": "Bellboy",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Front Office",
    "shiftName": "Morning Shift (8 AM-5 PM)",
    "positionName": "Driver(concierge/Valet )",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Front Office",
    "shiftName": "Morning Shift (9 AM- 6 PM)",
    "positionName": "Dir.Rooms/GRM",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Front Office",
    "shiftName": "Evening Shift(3 PM-12 AM )",
    "positionName": "Duty Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Front Office",
    "shiftName": "Evening Shift(3 PM-12 AM )",
    "positionName": "Receptionist",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Front Office",
    "shiftName": "Evening Shift(3 PM-12 AM )",
    "positionName": "Bellboy",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Front Office",
    "shiftName": "Overnight Shift(11 PM-8 AM)",
    "positionName": "Duty Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Front Office",
    "shiftName": "Overnight Shift(11 PM-8 AM)",
    "positionName": "Bellboy",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Front Office",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "11.789473684210526",
    "sun": 10,
    "mon": 10,
    "tue": 10,
    "wed": 10,
    "thu": 10,
    "fri": 10,
    "sat": 10,
    "weeklyTotal": 70
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Ned SPA",
    "shiftName": "Morning Shift (6 AM-3 PM)",
    "positionName": "Attendant",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Ned SPA",
    "shiftName": "Morning Shift (7AM-4 PM)",
    "positionName": "Life Guard",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Ned SPA",
    "shiftName": "Morning Shift (7 AM- 4 PM)",
    "positionName": "Fitness Ins.",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Ned SPA",
    "shiftName": "Morning Shift (9AM- 6 PM)",
    "positionName": "Spa Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Ned SPA",
    "shiftName": "Morning Shift (9 AM-6 PM)",
    "positionName": "Therapist",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Ned SPA",
    "shiftName": "Evening Shift(2PM-11PM )",
    "positionName": "Receptionist",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Ned SPA",
    "shiftName": "Evening Shift(2 PM-11 PM )",
    "positionName": "Therapist",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Ned SPA",
    "shiftName": "Evening Shift(3 PM-12 AM )",
    "positionName": "Attendant",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Ned SPA",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "9.4315789473684202",
    "sun": 8,
    "mon": 8,
    "tue": 8,
    "wed": 8,
    "thu": 8,
    "fri": 8,
    "sat": 8,
    "weeklyTotal": 56
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Housekeeping",
    "shiftName": "Morning Shift (8 AM- 5PM)",
    "positionName": "HK Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 0,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 4
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Housekeeping",
    "shiftName": "Morning Shift (8 AM- 5 PM)",
    "positionName": "HK Supervisor",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 0,
    "tue": 0,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 4
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Housekeeping",
    "shiftName": "Morning Shift (8 AM- 5 PM)",
    "positionName": "Room Attendant",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Housekeeping",
    "shiftName": "Morning Shift (8 AM- 5 PM)",
    "positionName": "Public Area",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 2,
    "mon": 2,
    "tue": 2,
    "wed": 2,
    "thu": 2,
    "fri": 2,
    "sat": 2,
    "weeklyTotal": 14
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Housekeeping",
    "shiftName": "Morning Shift (8 AM- 5 PM)",
    "positionName": "BOH Locker",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Housekeeping",
    "shiftName": "Morning Shift (8 AM-5 PM)",
    "positionName": "Laundry",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Housekeeping",
    "shiftName": "Evening Shift(3 PM-12 AM )",
    "positionName": "HK Supervisor",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 0,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 6
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Housekeeping",
    "shiftName": "Evening Shift(3 PM-12 AM )",
    "positionName": "TD Attendant",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Housekeeping",
    "shiftName": "Evening Shift(3 PM-12 AM )",
    "positionName": "Public Area",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 2,
    "mon": 2,
    "tue": 2,
    "wed": 2,
    "thu": 2,
    "fri": 2,
    "sat": 2,
    "weeklyTotal": 14
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Housekeeping",
    "shiftName": "Evening Shift(3 PM-12 AM )",
    "positionName": "Laundry",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Housekeeping",
    "shiftName": "Overnight Shift(11 AM-8 AM)",
    "positionName": "Public Area",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 4,
    "mon": 4,
    "tue": 4,
    "wed": 4,
    "thu": 4,
    "fri": 4,
    "sat": 4,
    "weeklyTotal": 28
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Housekeeping",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "17.684210526315791",
    "sun": 15,
    "mon": 15,
    "tue": 15,
    "wed": 15,
    "thu": 15,
    "fri": 15,
    "sat": 15,
    "weeklyTotal": 105
  },
  {
    "mainDepartment": "Rooms",
    "sheetName": "Rooms",
    "subDepartment": "Housekeeping",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "11.789473684210526",
    "sun": 0,
    "mon": 0,
    "tue": 0,
    "wed": 0,
    "thu": 0,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 0
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Security",
    "shiftName": "HOD",
    "positionName": "",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Security",
    "shiftName": "Morning Shift (07 AM - 4 PM)",
    "positionName": "Shift Leader",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Security",
    "shiftName": "Middle Shift (03 PM - 12 AM)",
    "positionName": "Shift Leader",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Security",
    "shiftName": "Night Shift (11 PM 08 AM)",
    "positionName": "Shift Leader",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Security",
    "shiftName": "Morning Shift (07:00 AM - 04 PM)",
    "positionName": "Guard- Security Office",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Security",
    "shiftName": "Middle Shift (15:00 PM 12 AM )",
    "positionName": "Guard- Security Office",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Security",
    "shiftName": "Evening Shift (23:00 PM - 08 AM)",
    "positionName": "Guard- Security Office",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Security",
    "shiftName": "WO Reliever for the entire team",
    "positionName": "WO Reliever for the entire team",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Security",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "9.4315789473684202",
    "sun": 8,
    "mon": 8,
    "tue": 8,
    "wed": 8,
    "thu": 8,
    "fri": 8,
    "sat": 8,
    "weeklyTotal": 56
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Hygiene",
    "shiftName": "Morning Shift (08 AM - 5 PM)",
    "positionName": "Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 5
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Hygiene",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "0.84210526315789469",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 5
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Engineering",
    "shiftName": "Morning Shift (07.00-04.00)",
    "positionName": "Supervisor",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 6
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Engineering",
    "shiftName": "Morning Shift (07.00-04.00)",
    "positionName": "Technician",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 0,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 6
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Engineering",
    "shiftName": "Evening Shift (15.00 - 00.00)",
    "positionName": "Supervisor",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 0,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 6
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Engineering",
    "shiftName": "Evening Shift (15.00 - 00.00)",
    "positionName": "Technician",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 0,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 6
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Engineering",
    "shiftName": "Night Shift (23.00-08.00)",
    "positionName": "Night In Charge",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 0,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 6
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Engineering",
    "shiftName": "Reliver (Assistant Manager)",
    "positionName": "Reliver (Assistant Manager)",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 0,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 4
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Engineering",
    "shiftName": "Director of Engineering",
    "positionName": "Director of Engineering",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 0,
    "tue": 0,
    "wed": 0,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 4
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Engineering",
    "shiftName": "General Shift (6:00pm)",
    "positionName": "Painter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 0,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 3
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Engineering",
    "shiftName": "General Shift (6:00pm)",
    "positionName": "Carpenter",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 0,
    "tue": 0,
    "wed": 0,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 3
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Engineering",
    "shiftName": "General Shift (6:00pm)",
    "positionName": "Coordinator",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 5
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Engineering",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "8.2526315789473692",
    "sun": 7,
    "mon": 7,
    "tue": 7,
    "wed": 7,
    "thu": 7,
    "fri": 7,
    "sat": 7,
    "weeklyTotal": 49
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Guest Experience",
    "shiftName": "Early (07:00 - 16:00)",
    "positionName": "Agent",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Guest Experience",
    "shiftName": "Admin (09:00 - 18:00)",
    "positionName": "Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 5
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Guest Experience",
    "shiftName": "Early Mid (10:00 - 19:00)",
    "positionName": "Agent",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Guest Experience",
    "shiftName": "Mid (12:00 - 21:00)",
    "positionName": "Assistant Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 6
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Guest Experience",
    "shiftName": "Late Mid (13:00 - 22:00)",
    "positionName": "Supervisor",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Guest Experience",
    "shiftName": "Late (15:00 - 00:00)",
    "positionName": "Agent",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 0,
    "weeklyTotal": 6
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Guest Experience",
    "shiftName": "Night (23:00 - 08:00)",
    "positionName": "Agent",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Guest Experience",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "7.5789473684210522",
    "sun": 6,
    "mon": 7,
    "tue": 7,
    "wed": 7,
    "thu": 7,
    "fri": 6,
    "sat": 5,
    "weeklyTotal": 45
  },
  {
    "mainDepartment": "Security & Eng",
    "sheetName": "Security&Eng",
    "subDepartment": "Total Count per Day",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "1.0105263157894737",
    "sun": 0,
    "mon": 0,
    "tue": 0,
    "wed": 0,
    "thu": 0,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 0
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Membership / Club",
    "shiftName": "Morning Shift (09:00 - 18:00)",
    "positionName": "",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Membership / Club",
    "shiftName": "Evening Shift (12:00 - 21:00)",
    "positionName": "",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Membership / Club",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "2.8354430379746836",
    "sun": 2,
    "mon": 2,
    "tue": 2,
    "wed": 2,
    "thu": 2,
    "fri": 2,
    "sat": 2,
    "weeklyTotal": 14
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Finance",
    "shiftName": "Morning Shift (09:00 - 18:00)",
    "positionName": "Director of Finance",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 0,
    "tue": 0,
    "wed": 1,
    "thu": 1,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 3
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Finance",
    "shiftName": "Morning Shift (09:00 - 18:00)",
    "positionName": "Asst. FC",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 1,
    "tue": 1,
    "wed": 0,
    "thu": 0,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 2
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Finance",
    "shiftName": "Morning Shift (09:00 - 18:00)",
    "positionName": "General Cashier/Paymaster",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 0,
    "tue": 0,
    "wed": 0,
    "thu": 1,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 2
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Finance",
    "shiftName": "Morning Shift (09:00 - 18:00)",
    "positionName": "Accounts Payable Supervisor",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 1,
    "tue": 0,
    "wed": 0,
    "thu": 1,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 2
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Finance",
    "shiftName": "Morning Shift (09:00 - 18:00)",
    "positionName": "AR Superviosr",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 1,
    "tue": 0,
    "wed": 1,
    "thu": 1,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 3
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Finance",
    "shiftName": "Morning Shift (09:00 - 18:00)",
    "positionName": "Day Auditor",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 0,
    "tue": 1,
    "wed": 0,
    "thu": 0,
    "fri": 0,
    "sat": 1,
    "weeklyTotal": 3
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Finance",
    "shiftName": "Morning Shift (09:00 - 18:00)",
    "positionName": "Cost Controller",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 0,
    "tue": 0,
    "wed": 0,
    "thu": 1,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 2
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Finance",
    "shiftName": "Morning Shift (09:00 - 18:00)",
    "positionName": "Receiving Officer",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 0,
    "wed": 0,
    "thu": 1,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 3
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Finance",
    "shiftName": "Morning Shift (09:00 - 18:00)",
    "positionName": "Storekeeper",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 0,
    "tue": 1,
    "wed": 1,
    "thu": 0,
    "fri": 0,
    "sat": 1,
    "weeklyTotal": 3
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Finance",
    "shiftName": "Morning Shift (09:00 - 18:00)",
    "positionName": "Purchasing Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 0,
    "wed": 0,
    "thu": 1,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 3
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Finance",
    "shiftName": "Morning Shift (09:00 - 18:00)",
    "positionName": "Purchasing Supervisor",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 0,
    "tue": 1,
    "wed": 1,
    "thu": 0,
    "fri": 0,
    "sat": 1,
    "weeklyTotal": 3
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Finance",
    "shiftName": "Morning Shift (09:00 - 18:00)",
    "positionName": "IT Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 0,
    "wed": 0,
    "thu": 1,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 3
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Finance",
    "shiftName": "Morning Shift (09:00 - 18:00)",
    "positionName": "IT Assistant",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 0,
    "tue": 1,
    "wed": 1,
    "thu": 0,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 4
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Finance",
    "shiftName": "Morning Shift (09:00 - 18:00)",
    "positionName": "AV Supervisor",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 0,
    "tue": 0,
    "wed": 0,
    "thu": 0,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 0
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Finance",
    "shiftName": "Morning Shift (09:00 - 18:00)",
    "positionName": "AV Technician",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 0,
    "tue": 1,
    "wed": 1,
    "thu": 0,
    "fri": 0,
    "sat": 1,
    "weeklyTotal": 3
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Finance",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "7.8987341772151902",
    "sun": 7,
    "mon": 6,
    "tue": 6,
    "wed": 6,
    "thu": 8,
    "fri": 1,
    "sat": 5,
    "weeklyTotal": 39
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "HR",
    "shiftName": "Morning Shift (08:00 - 17:00)",
    "positionName": "GRO Team",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 5
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "HR",
    "shiftName": "Morning Shift (09:00 - 18:00)",
    "positionName": "Director Of HR",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 0,
    "wed": 0,
    "thu": 1,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 3
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "HR",
    "shiftName": "Morning Shift (09:00 - 18:00)",
    "positionName": "L & D",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 4
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "HR",
    "shiftName": "Morning Shift (09:00 - 18:00)",
    "positionName": "HR Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 0,
    "tue": 1,
    "wed": 1,
    "thu": 0,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 3
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "HR",
    "shiftName": "Morning Shift (09:00 - 18:00)",
    "positionName": "HR Team",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 2,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 2,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "HR",
    "shiftName": "Morning Shift (09:00 - 18:00)",
    "positionName": "Housing Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 5
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "HR",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "5.4683544303797467",
    "sun": 6,
    "mon": 5,
    "tue": 5,
    "wed": 5,
    "thu": 6,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 27
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "BOH - Staff Stewarding",
    "shiftName": "Morning Shift (07:00 - 16:00)",
    "positionName": "Steward",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "BOH - Staff Stewarding",
    "shiftName": "Morning Shift (10:00 - 19:00)",
    "positionName": "Assistant Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 0,
    "sat": 1,
    "weeklyTotal": 6
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "BOH - Staff Stewarding",
    "shiftName": "MID Shift (13:00 - 20:00)",
    "positionName": "Steward",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "BOH - Staff Stewarding",
    "shiftName": "Afternoon Shift (14:00 - 21:00)",
    "positionName": "Steward",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 0,
    "tue": 0,
    "wed": 0,
    "thu": 0,
    "fri": 1,
    "sat": 0,
    "weeklyTotal": 1
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "BOH - Staff Stewarding",
    "shiftName": "Afternoon Shift (16:00 - 23:00)",
    "positionName": "Steward",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "BOH - Staff Stewarding",
    "shiftName": "Night Shift (23:00 - 08:00)",
    "positionName": "Steward",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "BOH - Staff Stewarding",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "7.0886075949367084",
    "sun": 5,
    "mon": 5,
    "tue": 5,
    "wed": 5,
    "thu": 5,
    "fri": 5,
    "sat": 5,
    "weeklyTotal": 35
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Sales & Marketing",
    "shiftName": "Morning Shift (09:00am)",
    "positionName": "Director of Sales & Marketing",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 0,
    "thu": 0,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 3
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Sales & Marketing",
    "shiftName": "Morning Shift (09:00am)",
    "positionName": "Sales Coordinator",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 5
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Sales & Marketing",
    "shiftName": "Morning Shift (09:00am)",
    "positionName": "Senior Manager of Events",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 0,
    "tue": 0,
    "wed": 0,
    "thu": 0,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 0
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Sales & Marketing",
    "shiftName": "Morning Shift (09:00am)",
    "positionName": "Events Executive",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 7
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Sales & Marketing",
    "shiftName": "Morning Shift (09:00am)",
    "positionName": "Assistant Director of Sales",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 0,
    "tue": 0,
    "wed": 1,
    "thu": 1,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 2
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Sales & Marketing",
    "shiftName": "Morning Shift (09:00am)",
    "positionName": "Sales Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 5
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Sales & Marketing",
    "shiftName": "Morning Shift (09:00am)",
    "positionName": "Revenue Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 5
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Sales & Marketing",
    "shiftName": "Morning Shift (09:00am)",
    "positionName": "Assistant Public Relations Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 5
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Sales & Marketing",
    "shiftName": "Morning Shift (09:00am)",
    "positionName": "Assistant Marketing Manager",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 0,
    "tue": 0,
    "wed": 0,
    "thu": 0,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 0
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Sales & Marketing",
    "shiftName": "Morning Shift (09:00am)",
    "positionName": "Brand Marketing Executive",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 1,
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 5
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Sales & Marketing",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "7.4936708860759493",
    "sun": 7,
    "mon": 7,
    "tue": 7,
    "wed": 7,
    "thu": 7,
    "fri": 1,
    "sat": 1,
    "weeklyTotal": 37
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Total Count per Day",
    "shiftName": "Total employee need for all shifts",
    "positionName": "Required FTE",
    "rowType": "summary",
    "requiredFte": "2.8354430379746836",
    "sun": 0,
    "mon": 0,
    "tue": 0,
    "wed": 0,
    "thu": 0,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 0
  },
  {
    "mainDepartment": "Admin",
    "sheetName": "Admin",
    "subDepartment": "Sun",
    "shiftName": "Summary",
    "positionName": "Departments",
    "rowType": "shift",
    "requiredFte": "",
    "sun": 0,
    "mon": 0,
    "tue": 0,
    "wed": 0,
    "thu": 0,
    "fri": 0,
    "sat": 0,
    "weeklyTotal": 0
  }
];

export const EXTRACTED_MAPPINGS = [
  {
    "sourceName": "F&B - Electric Diner",
    "targetName": "F&B - Electric"
  },
  {
    "sourceName": "F&B - Electric",
    "targetName": "F&B - Electric"
  },
  {
    "sourceName": "F&B - Cecconis",
    "targetName": "F&B - Ceecconi's"
  },
  {
    "sourceName": "F&B - Ceecconi's",
    "targetName": "F&B - Ceecconi's"
  },
  {
    "sourceName": "F&B - Kaia",
    "targetName": "F&B - Kaia"
  },
  {
    "sourceName": "F&B - Millies",
    "targetName": "F&B - Millies"
  },
  {
    "sourceName": "F&B - Malibu",
    "targetName": "F&B - Malibu"
  },
  {
    "sourceName": "F&B - Hadika",
    "targetName": "F&B - Hadika"
  },
  {
    "sourceName": "Cake Shop",
    "targetName": "Cake Shop"
  },
  {
    "sourceName": "F&B - Banquet OPS",
    "targetName": "F&B - Banquet"
  },
  {
    "sourceName": "F&B - Banquet",
    "targetName": "F&B - Banquet"
  },
  {
    "sourceName": "F&B - IRD",
    "targetName": "F&B - IRD"
  },
  {
    "sourceName": "F&B - Neds Club",
    "targetName": "F&B - Ned Club"
  },
  {
    "sourceName": "F&B - Ned Club",
    "targetName": "F&B - Ned Club"
  },
  {
    "sourceName": "F&B - Nickel Lounge",
    "targetName": "F&B - Nickel Lounge"
  },
  {
    "sourceName": "F&B - Admin",
    "targetName": "F&B - Admin"
  },
  {
    "sourceName": "Culinary - Neds Club",
    "targetName": "CUL - Neds Club"
  },
  {
    "sourceName": "CUL - Neds Club",
    "targetName": "CUL - Neds Club"
  },
  {
    "sourceName": "Culinary - Pastry",
    "targetName": "CUL - Pastry"
  },
  {
    "sourceName": "CUL - Pastry",
    "targetName": "CUL - Pastry"
  },
  {
    "sourceName": "Culinary - Millies",
    "targetName": "CUL - Millies"
  },
  {
    "sourceName": "CUL - Millies",
    "targetName": "CUL - Millies"
  },
  {
    "sourceName": "Culinary - Electric Diner",
    "targetName": "CUL - Electric"
  },
  {
    "sourceName": "CUL - Electric",
    "targetName": "CUL - Electric"
  },
  {
    "sourceName": "Culinary - Kaia",
    "targetName": "CUL - Kaia"
  },
  {
    "sourceName": "CUL - Kaia",
    "targetName": "CUL - Kaia"
  },
  {
    "sourceName": "Culinary - Malibu",
    "targetName": "CUL - Malibu"
  },
  {
    "sourceName": "CUL - Malibu",
    "targetName": "CUL - Malibu"
  },
  {
    "sourceName": "Culinary - Hadika",
    "targetName": "CUL - Hadika"
  },
  {
    "sourceName": "CUL - Hadika",
    "targetName": "CUL - Hadika"
  },
  {
    "sourceName": "Culinary - Banquet",
    "targetName": "CUL - Banquet"
  },
  {
    "sourceName": "CUL - Banquet",
    "targetName": "CUL - Banquet"
  },
  {
    "sourceName": "Culinary - Cecconis",
    "targetName": "CUL - Cecconis"
  },
  {
    "sourceName": "CUL - Cecconis",
    "targetName": "CUL - Cecconis"
  },
  {
    "sourceName": "Culinary - Admin",
    "targetName": "CUL - Admin"
  },
  {
    "sourceName": "CUL - Admin",
    "targetName": "CUL - Admin"
  },
  {
    "sourceName": "Culinary - Cafeteria",
    "targetName": "CUL - Cafeteria"
  },
  {
    "sourceName": "CUL - Cafeteria",
    "targetName": "CUL - Cafeteria"
  },
  {
    "sourceName": "Culinary - Butchery",
    "targetName": "CUL - Butchery"
  },
  {
    "sourceName": "CUL - Butchery",
    "targetName": "CUL - Butchery"
  },
  {
    "sourceName": "Culinary - QIA",
    "targetName": "CUL - QIA"
  },
  {
    "sourceName": "CUL - QIA",
    "targetName": "CUL - QIA"
  },
  {
    "sourceName": "Front Office",
    "targetName": "Front Office"
  },
  {
    "sourceName": "Spa & Wellness",
    "targetName": "Ned SPA"
  },
  {
    "sourceName": "Ned SPA",
    "targetName": "Ned SPA"
  },
  {
    "sourceName": "Housekeeping",
    "targetName": "Housekeeping"
  },
  {
    "sourceName": "Security",
    "targetName": "Security"
  },
  {
    "sourceName": "Hygiene",
    "targetName": "Hygiene"
  },
  {
    "sourceName": "Engineering",
    "targetName": "Engineering"
  },
  {
    "sourceName": "People & Development",
    "targetName": "HR"
  },
  {
    "sourceName": "HR",
    "targetName": "HR"
  },
  {
    "sourceName": "Membership",
    "targetName": "Membership / Club"
  },
  {
    "sourceName": "Membership / Club",
    "targetName": "Membership / Club"
  },
  {
    "sourceName": "Finance",
    "targetName": "Finance"
  },
  {
    "sourceName": "Cafeteria",
    "targetName": "Cafeteria"
  },
  {
    "sourceName": "Sales & Marketing",
    "targetName": "Sales & Marketing"
  },
  {
    "sourceName": "Admin & General",
    "targetName": "Admin & General"
  },
  {
    "sourceName": "Concierge",
    "targetName": "Concierge"
  },
  {
    "sourceName": "Guest Experience",
    "targetName": "Guest Experience"
  },
  {
    "sourceName": "BOH - Stewarding",
    "targetName": "BOH - Stewarding"
  },
  {
    "sourceName": "BOH - Staff Stewarding",
    "targetName": "BOH - Staff Stewarding"
  }
];